@startuml Class
!theme toy
class Boid {
    - position: PVector
    - velocity: PVector
    - acceleration: PVector
    - r: float
    - maxForce: float
    - maxSpeed: float
    __
    + Boid(float x, float y)
    + run(ArrayList<Boid> boids, color flockColor): void
    # applyForce(PVector force): void
    # flock(ArrayList<Boid> boids): void
    # updatePosition(): void
    # seek(PVector target): PVector
    # render(color flockColor): void
    # borders(): void
    # separate(ArrayList<Boid> boids): PVector
    - align(ArrayList<Boid> boids): PVector
    - cohesion(ArrayList<Boid> boids): PVector
}


    class Flock {
        -boids: List~Boid~
        -flockColor: color
        +Flock(color flockColor, int numBoids, boolean isPlayerControlled)
        -initializeBoids(int numBoids, boolean isPlayerControlled) void
        +run() void
        +addBoid(Boid boid) void
        +getBoids() List~Boid~
    }

        class PlayerControlledBoid {
        +PlayerControlledBoid(float x, float y)
        +run(ArrayList~Boid~ boids, color flockColor) void
    }

    Flock *-- Boid
    PlayerControlledBoid --|> Boid
    
@enduml